export const DEFAULT_CHAT_APPROVAL_TIMEOUT_MS = 300_000;
export const MAX_CACHED_CHAT_RUN_STREAMS = 100;
export const CHAT_RUN_STREAM_HEARTBEAT_INTERVAL_MS = 15_000;
export const MAX_CHAT_RUN_REPLAY_EVENTS = 512;
export const CHAT_COMPACTION_RESERVE_TOKEN_CAP = 16_384;
export const CHAT_COMPACTION_RECENT_TOKEN_CAP = 20_000;
